CREATE DATABASE BRSDB;
USE BRSDB;

CREATE TABLE DRIVER(
	DRIVER_ID VARCHAR(3),
    DRIVER_NAME VARCHAR(50) NOT NULL,
    DRIVER_PH BIGINT NOT NULL UNIQUE,
    PRIMARY KEY(DRIVER_ID)
);

INSERT INTO DRIVER VALUES("D1","RAMESH CHAVHAN",8808766542);
INSERT INTO DRIVER VALUES("D2","JIGNESH PATEL",8608766542);
INSERT INTO DRIVER VALUES("D3","RAMASHANKAR WAGHMARE",9808766542);
INSERT INTO DRIVER VALUES("D4","SUNIL MISHRA",8908766542);
INSERT INTO DRIVER VALUES("D5","JASPREET SINGH",8808066542);

SELECT * FROM DRIVER;

CREATE TABLE BUS(
	BUS_ID VARCHAR(3),
    BUS_NUMBER VARCHAR(10) NOT NULL UNIQUE,
    BUS_SEATS INT NOT NULL,
    START_POINT VARCHAR(50) NOT NULL,
    END_POINT VARCHAR(50) NOT NULL,
    DRIVER_ID VARCHAR(3) NOT NULL,
    PRIMARY KEY(BUS_ID),
    CONSTRAINT DFK FOREIGN KEY(DRIVER_ID) REFERENCES DRIVER(DRIVER_ID) 
);

INSERT INTO BUS VALUES("B1","DL1YB5592",55,"DELHI","BHOPAL","D1");
INSERT INTO BUS VALUES("B2","DL1YL5092",55,"DELHI","RAJASTHAN","D2");
INSERT INTO BUS VALUES("B3","DL1YB4592",55,"DELHI","NAGPUR","D3");
INSERT INTO BUS VALUES("B4","DL1YL5582",55,"DELHI","HYDERABAD","D4");
INSERT INTO BUS VALUES("B5","DL1YL5572",55,"DELHI","MUMBAI","D5");

SELECT * FROM BUS;

CREATE TABLE PASSENGER(
	PASSENGER_ID VARCHAR(3),
    PASSENGER_NAME VARCHAR(10) NOT NULL,
    GENDER VARCHAR(2) NOT NULL CHECK(GENDER IN("M","F","O","NS")) DEFAULT("NS"),
    AGE INT NOT NULL CHECK(AGE BETWEEN 1 AND 100),
    PASSENGER_PH BIGINT NOT NULL UNIQUE,
    PRIMARY KEY(PASSENGER_ID)
);

ALTER TABLE PASSENGER MODIFY COLUMN PASSENGER_NAME VARCHAR(50);

INSERT INTO PASSENGER VALUES("P1","REEMA THAKUR","F",27,9945322109);
INSERT INTO PASSENGER VALUES("P2","KARAN KHURANA","M",25,9745322109);
INSERT INTO PASSENGER VALUES("P3","VIJAY AGARWAL","M",35,9845322109);
INSERT INTO PASSENGER VALUES("P4","BATITA SINGH","F",40,9145322109);
INSERT INTO PASSENGER VALUES("P5","GEETA SINGH","F",38,9045322109);

SELECT * FROM PASSENGER;